### ISSUE TITLE
required assets in Rails5

### ISSUE THREAD

**Issue by exocode** [steakknife/svg-flags-rails#10]
In order to run properly in Rails5 you need to add 

```
Rails.application.config.assets.precompile += %w( country-4x3/* )
Rails.application.config.assets.precompile += %w( country-squared/* )
```

in ``initializers/assets.rb``

Please tell me if I am wrong

**Comment by steakknife** [comment]
1.0.0-beta3 fixes this and is complete. Will release when back to civilization.

**Comment by steakknife** [comment]
Give 1.0.0-beta3 a try, and if borks out for any reason, c'mon back.

**Comment by exocode** [comment]
Yes, looks good. Thank you!

**Comment by steakknife** [comment]
🍻
