### ISSUE TITLE
GB 4x3 flag is missing the red diagonal cross

### ISSUE THREAD

**Issue by Owumaro** [steakknife/svg-flags-rails#4]
Weird as the squared one has it.

https://github.com/steakknife/svg-flags-rails/blob/master/app/assets/images/country-4x3/gb.svg
vs
https://github.com/steakknife/svg-flags-rails/blob/master/app/assets/images/country-squared/gb.svg

**Comment by steakknife** [comment]
Patches welcomed!

**Comment by steakknife** [comment]
Resolved by #5. Thanks! 🍺
